version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: client_db
    environment:
      POSTGRES_DB: client_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: ./client-management-api
      dockerfile: Dockerfile
    container_name: client_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/client_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
  frontend:
    build:
      context: ./client-management-frontend
      dockerfile: Dockerfile
    container_name: client_frontend
    ports:
      - "3000:3000"
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    environment:
      SWAGGER_JSON: http://localhost:8080/v3/api-docs
      SWAGGER_JSON_URL: http://localhost:8080/v3/api-docs
    volumes:
      - ./swagger/swagger-config.json:/usr/share/nginx/html/swagger-config.json
    ports:
      - "8082:8080"
volumes:
  db_data:
