version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: client_db
    environment:
      POSTGRES_DB: client_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/client_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    environment:
      SWAGGER_JSON: /swagger/api-docs.json
    volumes:
      - ./swagger:/swagger
    ports:
      - "80:8081"
volumes:
  db_data:
